# Generated by Django 5.2.7 on 2025-10-22 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("domains", "0002_alter_domain_user_extra_attrs_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="domain",
            name="client_secret",
            field=models.CharField(max_length=255),
        ),
    ]
